# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Open a connection.
#'
#' Pass  a character data source name to the internal nc_open library function.
#' @param dsn data source name, i.e. file path or server path
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  Rnc_open(f_l3b)
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#'  Rnc_open(f_l3m)
#' u_cst <- "http://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQSwind3da"
#'  Rnc_open(u_cst)
Rnc_open <- function(dsn) {
    .Call(`_ncapi_Rnc_open`, dsn)
}

#' Close a connection.
#'
#' @param ncid file connection provided by `Rnc_open`
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3b)
#'  Rnc_close(con)
Rnc_close <- function(ncid) {
    invisible(.Call(`_ncapi_Rnc_close`, ncid))
}

#' Attribute details
#'
#' This is a structured list of the *names* of available attributes for
#' the given variable. "Global" is variable -1. See Rnc_inq_variable for
#' the variables and the number of attributes.
#' To get the attribute values we need to map its type to the right
#' function call of the API. This probably best done in R?
#' @param grpid con
#' @param varid variable id (can be global at -1)
#' @param attid attribute id (within variable)
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3m)
#'  vars <- tibble::as_tibble(Rnc_inq_variable(con))
#'  lapply(seq_len(vars$natts[1])-1, function(iatt) Rnc_inq_att(con, vars$id[1], iatt))
#'  Rnc_inq_att(con, vars$id[1], seq_len(vars$natts[1])[5])
#'  Rnc_close(con)
Rnc_inq_att <- function(grpid, varid, attid) {
    .Call(`_ncapi_Rnc_inq_att`, grpid, varid, attid)
}

#' We already know this from Rnc_inq_variable
#'
#' @param grpid con
#' @param varid variable id
#'
Rnc_inq_natts <- function(grpid, varid) {
    .Call(`_ncapi_Rnc_inq_natts`, grpid, varid)
}

#' Inquire group IDs
#'
#' @inheritParams Rnc_close
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3b)
#'  Rnc_inq_grps(con)
#'  Rnc_close(con)
Rnc_inq_grps <- function(ncid) {
    .Call(`_ncapi_Rnc_inq_grps`, ncid)
}

#' Inquire group name by ID
#'
#' @param grpid group ID provided by `Rnc_inq_grps`
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3b)
#'  groupids <- Rnc_inq_grps(con)
#'  Rnc_inq_grpname(groupids[1])
#'  lapply(Rnc_inq_grps(con), Rnc_inq_grpname)
#'  Rnc_close(con)
Rnc_inq_grpname <- function(grpid) {
    .Call(`_ncapi_Rnc_inq_grpname`, grpid)
}

#' Dimension inquiry
#'
#' @inheritParams Rnc_inq_grpname
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#' con <- Rnc_open(f_l3b)
#' groupids <- Rnc_inq_grps(con)
#' Rnc_inq_dimension(groupids[1])
#' Rnc_close(con)
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#' con <- Rnc_open(f_l3m)
#' ## watch out because if only one, the file con is the one
#' ##groupids <- Rnc_inq_grps(con)
#' tibble::as_tibble(Rnc_inq_dimension(con))
#' Rnc_close(con)
#' ## that should be the same as
#' #ncmeta::nc_dims(f_l3m)
Rnc_inq_dimension <- function(grpid) {
    .Call(`_ncapi_Rnc_inq_dimension`, grpid)
}

#' Variable inquiry
#'
#' @inheritParams Rnc_inq_grpname
#' @export
#' @examples
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#' con <- Rnc_open(f_l3m)
#' tibble::as_tibble(Rnc_inq_variable(con))
#' Rnc_close(con)
#' ## that should be the same as
#' # ncmeta::nc_vars(f_l3m)
#' # # A tibble: 4 x 5
#' #   id    name  type ndims natts
#' #   <int>   <chr> <chr> <int> <int>
#' #   0     chlor_a float     2    12
#' #   1     lat float     1     5
#' #   2     lon float     1     5
#' #   3     palette ubyte     2     0
Rnc_inq_variable <- function(grpid) {
    .Call(`_ncapi_Rnc_inq_variable`, grpid)
}

#' Dimensions of variables
#'
#' @inheritParams Rnc_inq_grpname
#' @param ivar index of variable
#' @export
#' @examples
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#' con <- Rnc_open(f_l3m)
#' variables <- tibble::as_tibble(Rnc_inq_variable(con))
#'  setNames(lapply(variables$id, function(x) Rnc_inq_vardims(con, x)), variables$name)
#' Rnc_close(con)
Rnc_inq_vardims <- function(grpid, ivar) {
    .Call(`_ncapi_Rnc_inq_vardims`, grpid, ivar)
}

#' Source inquiry
#'
#' once we have a given ID (group-less file, or specific group)
#' find its contents
#' @inheritParams Rnc_inq_grpname
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3b)
#'  groupids <- Rnc_inq_grps(con)
#'  l3b <- Rnc_inq(groupids[1])
#'  Rnc_close(con)
#'  print(basename(f_l3b))
#'  print(l3b)
#'  f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
Rnc_inq <- function(grpid) {
    .Call(`_ncapi_Rnc_inq`, grpid)
}

#' Dimension inquiry
#'
#' @inheritParams Rnc_inq_grpname
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#' con <- Rnc_open(f_l3b)
#' groupids <- Rnc_inq_grps(con)
#' Rnc_inq_dims(groupids[1])
#' Rnc_close(con)
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#' # ncmeta::nc_dims(f_l3m)
#' # A tibble: 4 x 4
#'       id          name length unlim
#'  <int>         <chr>  <dbl> <lgl>
#'  1     0           lat   2160 FALSE
#'  2     1           lon   4320 FALSE
#'  3     2           rgb      3 FALSE
#'  4     3 eightbitcolor    256 FALSE
Rnc_inq_dims <- function(grpid) {
    .Call(`_ncapi_Rnc_inq_dims`, grpid)
}

