# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Open a connection.
#'
#' Pass  a character data source name to the internal nc_open library function.
#' @param dsn data source name, i.e. file path or server path
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  Rnc_open(f_l3b)
#' f_l3m <- system.file("extdata", "oceandata", "S2008001.L3m_DAY_CHL_chlor_a_9km.nc", package = "ncapi")
#'  Rnc_open(f_l3m)
#' u_cst <- "http://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQSwind3da"
#'  Rnc_open(u_cst)
Rnc_open <- function(dsn) {
    .Call(`_ncapi_Rnc_open`, dsn)
}

#' Close a connection.
#'
#' @param ncid file connection provided by `Rnc_open`
#' @export
#' @examples
#' f_l3b <- system.file("extdata", "oceandata", "S2008001.L3b_DAY_CHL.nc", package = "ncapi")
#'  con <- Rnc_open(f_l3b)
#'  Rnc_close(con)
Rnc_close <- function(ncid) {
    invisible(.Call(`_ncapi_Rnc_close`, ncid))
}

Rnc_inq_grps <- function(ncid) {
    .Call(`_ncapi_Rnc_inq_grps`, ncid)
}

Rnc_inq_grpname <- function(grpid) {
    .Call(`_ncapi_Rnc_inq_grpname`, grpid)
}

